title: "Advokat Dejan Vasiljević"
description: "Advokat Dejan Vasiljević iz Zemuna nudi pravno savetovanje i zastupanje u parnicama, krivičnim, radnim i privrednim sporovima."
lang: sr

# Use docs/ as the Jekyll source so existing structure keeps working
source: docs
destination: _site
markdown: kramdown
permalink: pretty

# Plugins commonly allowed on GitHub Pages
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - node_modules
  - package.json
  - package-lock.json
  - input.css
  - README.md
  - .gitignore
  - avatar.jpg

defaults:
  - scope:
      path: ""
    values:
      layout: default
