title: "Advokat Dejan Vasiljević"
description: "Advokat Dejan Vasiljević iz Zemuna nudi pravno savetovanje i zastupanje u parnicama, krivičnim, radnim i privrednim sporovima."
lang: sr

markdown: kramdown
permalink: pretty

exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - postcss.config.js
  - tailwind.config.js

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-postcss-v2
